blank_issues_enabled: false
contact_links:
  - name: Velocity Support Server
    url: https://discord.gg/dvTE7gXanj
    about: If you need help regarding Velocity, please join our support server!
  - name: Velocity Installer
    url: https://github.com/ROBOXNOTHACKER/Installer
    about: You can find the Velocity Installer here
